/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vews;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Zita_Office
 */
public class PainelQuartos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaQuartos
     */
    public PainelQuartos() {
        super(null,false,false,false);
        initComponents();
        
        PainelQuartos.setLayout(new MigLayout("wrap 5"));
        PainelQuartos.setBackground(new Color(0,0,0,1));   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("1opcao.jpg"));
        Image image = icon.getImage();
        HomeConteiner = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PainelQuartos = new javax.swing.JPanel();
        quarto1 = new javax.swing.JPanel();
        quarto2 = new javax.swing.JPanel();
        quarto3 = new javax.swing.JPanel();
        quarto4 = new javax.swing.JPanel();
        quarto5 = new javax.swing.JPanel();
        quarto6 = new javax.swing.JPanel();
        quarto7 = new javax.swing.JPanel();
        quarto8 = new javax.swing.JPanel();
        quarto9 = new javax.swing.JPanel();
        quarto10 = new javax.swing.JPanel();
        quarto11 = new javax.swing.JPanel();
        quarto12 = new javax.swing.JPanel();
        quarto13 = new javax.swing.JPanel();
        quarto14 = new javax.swing.JPanel();
        quarto15 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(895, 665));

        HomeConteiner.setPreferredSize(new java.awt.Dimension(901, 50));
        HomeConteiner.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,70));
        jPanel1.setPreferredSize(new java.awt.Dimension(901, 50));
        jPanel1.setLayout(new FlowLayout(FlowLayout.LEFT));

        jLabel6.setText(" ");
        jPanel1.add(jLabel6);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,1));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GreenCircle.png"))); // NOI18N
        jLabel3.setText("Disponivel");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(jPanel4);

        jPanel3.setBackground(new java.awt.Color(0,0,0,1));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BlueCircle.png"))); // NOI18N
        jLabel4.setText("Reservado");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel3);

        jPanel8.setBackground(new java.awt.Color(0,0,0,1));
        jPanel8.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedCircle.png"))); // NOI18N
        jLabel5.setText("Ocupado");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(0,0,0,1));
        jPanel9.setPreferredSize(new java.awt.Dimension(156, 30));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GreyCircle.png"))); // NOI18N
        jLabel7.setText("Em Manutencao");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        jPanel1.add(jPanel9);

        HomeConteiner.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        PainelQuartos.setBackground(new Color(0,0,0,1));
        PainelQuartos.setPreferredSize(new java.awt.Dimension(895, 665));

        quarto1.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto1.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto1Layout = new javax.swing.GroupLayout(quarto1);
        quarto1.setLayout(quarto1Layout);
        quarto1Layout.setHorizontalGroup(
            quarto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto1Layout.setVerticalGroup(
            quarto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto2.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto2.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto2Layout = new javax.swing.GroupLayout(quarto2);
        quarto2.setLayout(quarto2Layout);
        quarto2Layout.setHorizontalGroup(
            quarto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto2Layout.setVerticalGroup(
            quarto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto3.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto3.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto3Layout = new javax.swing.GroupLayout(quarto3);
        quarto3.setLayout(quarto3Layout);
        quarto3Layout.setHorizontalGroup(
            quarto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto3Layout.setVerticalGroup(
            quarto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto4.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto4.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto4Layout = new javax.swing.GroupLayout(quarto4);
        quarto4.setLayout(quarto4Layout);
        quarto4Layout.setHorizontalGroup(
            quarto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto4Layout.setVerticalGroup(
            quarto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto5.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto5.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto5Layout = new javax.swing.GroupLayout(quarto5);
        quarto5.setLayout(quarto5Layout);
        quarto5Layout.setHorizontalGroup(
            quarto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto5Layout.setVerticalGroup(
            quarto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto6.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto6.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto6Layout = new javax.swing.GroupLayout(quarto6);
        quarto6.setLayout(quarto6Layout);
        quarto6Layout.setHorizontalGroup(
            quarto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto6Layout.setVerticalGroup(
            quarto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto7.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto7.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto7Layout = new javax.swing.GroupLayout(quarto7);
        quarto7.setLayout(quarto7Layout);
        quarto7Layout.setHorizontalGroup(
            quarto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto7Layout.setVerticalGroup(
            quarto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto8.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto8.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto8Layout = new javax.swing.GroupLayout(quarto8);
        quarto8.setLayout(quarto8Layout);
        quarto8Layout.setHorizontalGroup(
            quarto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto8Layout.setVerticalGroup(
            quarto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto9.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto9.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto9Layout = new javax.swing.GroupLayout(quarto9);
        quarto9.setLayout(quarto9Layout);
        quarto9Layout.setHorizontalGroup(
            quarto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto9Layout.setVerticalGroup(
            quarto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto10.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto10.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto10Layout = new javax.swing.GroupLayout(quarto10);
        quarto10.setLayout(quarto10Layout);
        quarto10Layout.setHorizontalGroup(
            quarto10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto10Layout.setVerticalGroup(
            quarto10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto11.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto11.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto11Layout = new javax.swing.GroupLayout(quarto11);
        quarto11.setLayout(quarto11Layout);
        quarto11Layout.setHorizontalGroup(
            quarto11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto11Layout.setVerticalGroup(
            quarto11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto12.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto12.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto12Layout = new javax.swing.GroupLayout(quarto12);
        quarto12.setLayout(quarto12Layout);
        quarto12Layout.setHorizontalGroup(
            quarto12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto12Layout.setVerticalGroup(
            quarto12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto13.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto13.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto13Layout = new javax.swing.GroupLayout(quarto13);
        quarto13.setLayout(quarto13Layout);
        quarto13Layout.setHorizontalGroup(
            quarto13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto13Layout.setVerticalGroup(
            quarto13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto14.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto14.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto14Layout = new javax.swing.GroupLayout(quarto14);
        quarto14.setLayout(quarto14Layout);
        quarto14Layout.setHorizontalGroup(
            quarto14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto14Layout.setVerticalGroup(
            quarto14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        quarto15.setBackground(new java.awt.Color(255, 255, 255,90));
        quarto15.setPreferredSize(new java.awt.Dimension(300, 250));

        javax.swing.GroupLayout quarto15Layout = new javax.swing.GroupLayout(quarto15);
        quarto15.setLayout(quarto15Layout);
        quarto15Layout.setHorizontalGroup(
            quarto15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        quarto15Layout.setVerticalGroup(
            quarto15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PainelQuartosLayout = new javax.swing.GroupLayout(PainelQuartos);
        PainelQuartos.setLayout(PainelQuartosLayout);
        PainelQuartosLayout.setHorizontalGroup(
            PainelQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelQuartosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelQuartosLayout.createSequentialGroup()
                        .addComponent(quarto11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quarto14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quarto15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quarto12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quarto13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelQuartosLayout.createSequentialGroup()
                        .addGroup(PainelQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelQuartosLayout.createSequentialGroup()
                                .addComponent(quarto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quarto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quarto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quarto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quarto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelQuartosLayout.createSequentialGroup()
                                .addComponent(quarto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quarto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quarto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quarto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quarto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelQuartosLayout.setVerticalGroup(
            PainelQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelQuartosLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(PainelQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quarto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(quarto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quarto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quarto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quarto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(PainelQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quarto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(quarto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quarto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quarto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quarto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(PainelQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quarto11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(quarto13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quarto12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quarto15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quarto14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        HomeConteiner.add(PainelQuartos, java.awt.BorderLayout.CENTER);

        getContentPane().add(HomeConteiner, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomeConteiner;
    private javax.swing.JPanel PainelQuartos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel quarto1;
    private javax.swing.JPanel quarto10;
    private javax.swing.JPanel quarto11;
    private javax.swing.JPanel quarto12;
    private javax.swing.JPanel quarto13;
    private javax.swing.JPanel quarto14;
    private javax.swing.JPanel quarto15;
    private javax.swing.JPanel quarto2;
    private javax.swing.JPanel quarto3;
    private javax.swing.JPanel quarto4;
    private javax.swing.JPanel quarto5;
    private javax.swing.JPanel quarto6;
    private javax.swing.JPanel quarto7;
    private javax.swing.JPanel quarto8;
    private javax.swing.JPanel quarto9;
    // End of variables declaration//GEN-END:variables
}
